sudo: required
dist: trusty
language: node_js
node_js:
  - 7
branches:
  only:
  - master
  - develop

services:
  - docker

#------------------------------------------------

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - sh -e /etc/init.d/xvfb start

instal: true

before_script:
  - npm run eslint
  - npm run stylelint
  - npm test
  - npm run webpack

script:
  - docker login --username=_ --password=$(echo $API_KEY) registry.heroku.com
  - docker build -t registry.heroku.com/hexandria-develop/web .
  - docker push registry.heroku.com/hexandria-develop/web
